- name: Установить Nginx на CentOS
  hosts: all
  become: true
  tasks:
    - name: Установить Nginx
      yum:
        name: nginx
        state: present
      register: ngix_install_result    

    - name: Отобразить прогресс выполнения
      debug:
        msg: "{{ item }}"
      loop: "{{ ngix_install_result.results }}"

    - name: Запустить и включить Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    
    - name: Установить firewalld
      yum:
        name: firewalld
        state: present

    - name: Запустить и включить firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: открыть http порт
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: yes     

